(function(d){"function"===typeof define&&define.amd?(define("klarna/terms",["klarna/core"],d),require(["klarna/terms"])):d(Klarna)})(function(d){(function(){var b=!1,h=/xyz/.test(function(){})?/\b_super\b/:/.*/,f=function(){};f.extend=function(c){function g(){!b&&this.init&&this.init.apply(this,arguments)}var d=this.prototype;b=!0;var f=new this;b=!1;for(var a in c)f[a]="function"==typeof c[a]&&"function"==typeof d[a]&&h.test(c[a])?function(a,c){return function(){var b=this._super;this._super=d[a];
var g=c.apply(this,arguments);this._super=b;return g}}(a,c[a]):c[a];g.prototype=f;g.prototype.constructor=g;g.extend=arguments.callee;return g};d.extend("Klarna",{KClass:f,Class:function(c,b,h){var k={},a=c.split("."),c=a.pop(),a=a.join(".")||"Klarna",j="undefined"!=typeof h,b=(j?b:f).extend(j?h:b);k[c]=b;d.extend(a,k);return b},subclass:function(c,b,h){var f={},a=c.split("."),c=a.pop(),a=a.join(".")||"Klarna",b=d.use(b),h=b.extend(h);f[c]=h;d.extend(a,f);return h}})})();(function(){var b=d._,h=d.use("Event"),
f=d.use("util");d.extend(f,{style:function(c){return"undefined"!=typeof c.currentStyle?c.currentStyle:document.defaultView.getComputedStyle(c,null)},$:function(c){return b.isString(c)?document.getElementById(c):c},waitForEntity:function(c,b,d){function f(){c[b]&&(h.unbind(j,a),d())}var a,j;j=h.makeName(["extended",c]);a=h.bind(j,f);f()}})})();(function(b){function d(){var a=0,c=0;if(document.body&&document.body.offsetWidth)a=document.body.offsetWidth,c=document.body.offsetHeight;if("CSS1Compat"===
document.compatMode&&document.documentElement&&document.documentElement.offsetWidth)a=document.documentElement.offsetWidth,c=document.documentElement.offsetHeight;if(window.innerWidth&&window.innerHeight)a=window.innerWidth,c=window.innerHeight;return{height:c,width:a}}var f=b.KClass,c=b._,g=b.use("Event"),l=b.use("util").$,k=b.use("Terms");b.extend(k,{Base:f.extend({init:function(){this.baseUrl="https://cdn.klarna.com/1.0/shared/content/legal/terms";this.legacyCountries={se:["se","swe"],dk:["dk",
"dnk"],no:["no","nok","nor"],fi:["fi","fin"],de:["de","deu"],nl:["nl","nld"]};this.defaultLanguage={se:"sv",dk:"da",no:"nb",fi:"fi",de:"de",nl:"nl",at:"de"};this.options={eid:0,lang:"",country:"",locale:"",el:null,placeholder:null,openPopupCallback:null,closePopupCallback:null,t:{},type:"desktop"}},getParams:function(){return{}},getAnchor:function(){return this.get("anchor")?this.get("anchor"):!0===this.get("microsite")?this.get("campaign"):""},getUrl:function(){var a=c.param(this.getParams()),b=
this.getAnchor(),e;e=[this.baseUrl,this.get("eid"),this.get("locale"),this.get("microsite")?"microsite":this.get("campaign")].join("/");a&&(e+="?"+a);b&&(e+="#"+b);return e},setup:function(a){this.options=c.extend(this.options,a);if(this.options.locale)this.setLocale(this.options.locale);else if(this.options.country)this.applyLegacyFixes(this.options.country);else throw Error("Locale must be specified.");g.bind("change:country",c.bind(this.applyLegacyFixes,this));g.bind("change:country",c.bind(this.renderLink,
this));g.bind("change:locale",c.bind(this.setLocale,this));g.bind("change:locale",c.bind(this.renderLink,this))},_onLinkClick:function(a){this.onLinkClick.call(this,a);"function"===typeof this.options.openPopupCallback&&this.options.openPopupCallback.call(this);return!1},_onCloseClick:function(a){this.onCloseClick.call(this,a);"function"===typeof this.options.closePopupCallback&&this.options.closePopupCallback.call(this);return!1},onLinkClick:function(){"mobile"===this.options.type?window.open(this.getUrl()):
this.openPopup({url:this.getUrl()})},onCloseClick:function(){this.destroyPopup()},get:function(a){return this.options[a]},set:function(a,c){this.options[a]=c;g.trigger("change:"+a,c,this)},t:function(a){return(this.options.t[a]||{})[this.get("locale")]},applyLegacyFixes:function(a){var b;if(!c.isString(a))throw Error("Country must be a string");a=a.toLowerCase();b=c(this.legacyCountries).filter(function(b){return c(b).include(a)});if(b.length)this.options.country=c(b).flatten()[0];this.options.locale=
(this.defaultLanguage[this.get("country")]+"_"+this.get("country")).toLowerCase()},createLink:function(){var a=l(this.options.el),b=l(this.options.placeholder),e;if(!a&&!b)throw Error("Please provide an existing DOM element where to create the link");e=b?b:document.createElement("a");e.id=this.options.id||"klarna-link-dynamic-"+this.get("country");e.className=this.options.linkClassName||"klarna-link";e.style.cursor="pointer";try{e.href="#",e.innerHTML=this.options.linkText}catch(d){}b||a.appendChild(e);
e.onclick=c.bind(this._onLinkClick,this);this.link=e},renderLink:function(){this.link.innerHTML=this.t("link.text")},popupDefaults:function(){var a={popupWidth:550,popupHeight:550,popupBackgroundColor:"#F1F1F1"};if(this.options.microsite)a.popupWidth=690,a.popupBackgroundColor="#FFFFFF";return a},openPopup:function(a){var b,e,f,g,i=d();e=500>i.width||i.width<a.popupWidth?0.9*i.width:a.popupWidth||500;i=515>i.height?0.9*i.height-15:500;a=a||{};c.defaults(a,this.popupDefaults());this.destroyPopup();
f=document.createElement("div");c.each({position:"fixed",top:0,left:0,width:"100%",zIndex:9998},function(a,b){f.style[b]=a});this.positioner=f;b=document.createElement("div");b.id="klarna-terms-popup";e={display:"block",backgroundColor:a.popupBackgroundColor,border:"solid 1px grey",width:e+"px",maxWidth:"90%",height:i+"px",position:"relative",marginLeft:"auto",marginRight:"auto",marginTop:"15px",padding:"25px 0 10px 0",zIndex:9999,borderRadius:"10px","-moz-border-radius":"10px","-webkit-border-radius":"10px"};
if("CSS1Compat"!==document.compatMode)e.position="absolute";c.extend(e,a.popupCss);c.each(e,function(a,c){b.style[c]=a});this.popup=b;g=document.createElement("div");c.each({overflow:"auto","-webkit-overflow-scrolling":"touch",height:"100%"},function(a,b){g.style[b]=a});b.appendChild(g);this.container=g;e=document.createElement("iframe");e.id="klarna-terms-iframe";e.width="100%";e.height="100%";e.frameBorder=0;e.style.border=0;e.style.display="block";e.src=a.url;g.appendChild(e);this.iframe=e;a=document.createElement("a");
a.href="#";a.style.color="grey";a.id="klarna-terms-popup-close";a.style.position="absolute";a.style.borderLeft="1px solid";a.style.borderBottom="1px solid";try{a.style.borderColor="rgba(0, 0, 0, 0.1)"}catch(k){a.style.borderColor="grey"}a.style.top="0";a.style.right="0";a.style.textDecoration="none";a.style.height="25px";a.style.width="25px";a.style.textAlign="center";a.style.verticalAlign="middle";a.style.lineHeight="25px";a.style.fontSize="17px";a.innerHTML="&times;";a.onclick=c.bind(this._onCloseClick,
this);this.closeButton=a;b.appendChild(a);a=document.createElement("div");a.style.position="fixed";a.style.top=0;a.style.left=0;a.style.width="100%";a.style.height="100%";a.style.background="#000";a.style.opacity=0.5;a.style.filter="alpha(opacity=50)";a.style.zIndex=9997;a.onclick=c.bind(this._onCloseClick,this);this.overlay=a;f.appendChild(b);document.body.insertBefore(a,null);document.body.insertBefore(f,null)},destroyPopup:function(){if(this.iframe)this.overlay.parentNode.removeChild(this.overlay),
this.overlay=null,this.positioner.parentNode.removeChild(this.positioner),this.positioner=null,this.iframe.parentNode.removeChild(this.iframe),this.iframe=null,this.container.parentNode.removeChild(this.container),this.container=null,this.popup.parentNode.removeChild(this.popup),this.popup=null},setLocale:function(a){if(!c.isString(a))throw Error("Locale must be a string");var b=a.match(/([a-zA-Z]{2})_([a-zA-Z]{2})/);if(!b)throw Error("Wrong locale format!");this.options.locale=a.toLowerCase();this.options.country=
b[2].toLowerCase()}})})})(d);(function(){var b=d.use("Terms");d.extend(b,{Account:b.Base.extend({init:function(b){this._super();this.setup(b);this.options.campaign="account";this.options.t["link.text"]={sv_se:"L&auml;s mer",sv_fi:"L&auml;s mer",en_se:"Read more",da_dk:"L&aelig;s mere",en_dk:"Read more",nb_no:"Les mer",en_no:"Read more",fi_fi:"Lue lis&auml;&auml;",en_fi:"Read more",de_de:"Lesen Sie mehr!",en_de:"Read more",nl_nl:"Lees meer!",en_nl:"Read more",de_at:"Lesen Sie mehr!",en_at:"Read more"};
this.options.linkText||this.set("linkText",this.t("link.text"));this.createLink()}})})})(this);(function(){var b=d._,h=d.use("Terms");d.extend(h,{Invoice:h.Base.extend({init:function(b){this._super();this.setup(b);this.options.campaign="invoice";this.options.t["link.text"]={sv_se:"Villkor f&ouml;r faktura",sv_fi:"Villkor f&ouml;r faktura",en_se:"Terms for Invoice",da_dk:"Vilk&aring;r for faktura",en_dk:"Terms for Invoice",nb_no:"Vilk&aring;r for faktura",en_no:"Terms for Invoice",fi_fi:"Laskuehdot",
en_fi:"Terms for Invoice",de_de:"Rechnungsbedingungen",en_de:"Terms for Invoice",nl_nl:"Factuurvoorwaarden",en_nl:"Terms for Invoice",de_at:"Rechnungsbedingungen",en_at:"Terms for Invoice"};this.options.charge||this.set("charge",0);this.options.linkText||this.set("linkText",this.t("link.text"));this.createLink()},getParams:function(){var d={};if(!b.isUndefined(this.options.charge))d.fee=this.options.charge;if(!b.isUndefined(this.options.credit_time))d.credit_time=this.options.credit_time;return d}})})})(this);
(function(){var b=d.use("Terms");d.extend(b,{Special:b.Base.extend({init:function(b){this._super();this.setup(b);this.options.t["link.text"]={sv_se:"L&auml;s mer",sv_fi:"L&auml;s mer",en_se:"Read more",da_dk:"L&aelig;s mere",en_dk:"Read more",nb_no:"Les mer",en_no:"Read more",fi_fi:"Lue lis&auml;&auml;",en_fi:"Read more",de_de:"Lesen Sie mehr!",en_de:"Read more",nl_nl:"Lees meer!",en_nl:"Read more",de_at:"Lesen Sie mehr!",en_at:"Read more"};this.options.campaign||this.set("campaign","campaign");
this.options.linkText||this.set("linkText",this.t("link.text"));this.createLink()}})})})(this);(function(){var b=d.use("Terms");d.extend(b,{Consent:b.Base.extend({init:function(b){this._super();this.setup(b);this.options.campaign="consent";this.options.t["link.text"]={de_de:"Einwilligung",en_de:"Consent",de_at:"Einwilligung",en_at:"Consent"};this.options.linkText||this.set("linkText",this.t("link.text"));this.createLink()}})})})(this)});
